### ISSUE TITLE
High-level overview of document structure

### ISSUE THREAD

**Issue by brettz9** [alpheios-project/lan#5]
Hi,

Although some of the XML mark-up seems based on the Text Encoding Initiative (TEI) dialect of XML, e.g., in use of [`entryFree`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-entryFree.html), the markup seems to differ somewhat, at least from the current TEI version (e.g., adding a `key` attribute to `entryFree`).

In looking at your indexes of the form:

```xml
    <entry lemma="اشبّهُ ٱللّٰهُ" key="اشبّهُ ٱللّٰهُ" id="n21523" i="1"/>
    <entry lemma="اشبّهُ ٱللّٰهُ" key="اشبّه ٱللّه" id="n21523" i="4"/>
    <entry lemma="اشبّهُ ٱللّٰهُ" key="اشبه ٱلله" id="n21523" i="5"/>
    <entry lemma="شُبَّ" key="شُبَّ" id="n21523" i="1"/>
    <entry lemma="شُبَّ" key="شبّ" id="n21523" i="4"/>
    <entry lemma="شُبَّ" key="شب" id="n21523" i="5"/>
```

I understand `lemma` to be the dictionary-friendly root, and I'm guessing that `key` may be related to the fact that a single entry may have different `<form>`'s perhaps. However, I am not discerning the pattern by which `i` might be used to correspond to tags and their sequence.

For example, in looking at the following entry (the only referencing `n21523`):

```xml
<entryFree id="n21523" key="اشبّهُ ٱللّٰهُ" type="main">
    <form>
      <itype>4</itype> 
      <orth orig="" extent="full" lang="ar">اشبّهُ ٱللّٰهُ</orth></form> <hi rend="ital">God made him,</hi> or <hi rend="ital">may God make
him, to become a youth,</hi> or <hi rend="ital">young man;</hi> i. e.,
<hi rend="ital">to attain to the state termed</hi> <foreign lang="ar">شَبَابٌ</foreign> <hi rend="ital">meaning as
expl. below:</hi> and <foreign lang="ar">اشبّ ٱللّٰهُ قَرْنَهُ</foreign> means the same:
(S, A, TA:) the latter [lit. means <hi rend="ital">God made,</hi> or
<hi rend="ital">may God make, his equal in age to become a
youth,</hi> &amp;c., (see Har p. 572,) and therefore] is
tropical. (A, TA.) ― 
       <milestone unit="sense" n="2"/>-b2-  <foreign lang="ar">أَشْبَيْتُ الفَرَسَ</foreign> <hi rend="ital">I excited the
horse to be brisk, lively,</hi> or <hi rend="ital">sprightly, and to raise
his fore legs together, as though in leaping, and
to play.</hi> (S, * K, * TA.) ― 
       <milestone unit="sense" n="2"/>-b3-  <foreign lang="ar">اشبّ النَّارَ</foreign>: see 1. ― 
       <milestone unit="sense" n="2"/>-b4- 
<foreign lang="ar">أُشِبَّ لِىَ الرَّجُلُ</foreign>, inf. n. <foreign lang="ar">إِشْبَابٌ</foreign>; as also ↓ <orth type="arrow" lang="ar">شُبَّ</orth>; (tropical:)  <hi rend="ital">The
man appeared before my upraised eyes when not
hoped for.</hi> (AZ, TA.) ― 
       <milestone unit="sense" n="2"/>-b5-  And <foreign lang="ar">أُشِبَّ لِى كَذَا</foreign>, and
↓ <orth type="arrow" lang="ar">شُبَّ</orth>, (tropical:)  <hi rend="ital">Such a thing was prepared,</hi> or <hi rend="ital">appointed,</hi>
or <hi rend="ital">ordained, for me.</hi> (S, K, * TA.) ＝   
    <milestone unit="sense" n="1"/>-A2-  <foreign lang="ar">أَشَبُّ</foreign> (tropical:)  <hi rend="ital">He
became one whose child,</hi> or <hi rend="ital">children, had attained
to the state of</hi> <foreign lang="ar">شَبَاب</foreign> [i. e. <hi rend="ital">youth,</hi> or <hi rend="ital">young manhood,</hi> &amp;c.]: (K:) [or] <foreign lang="ar">أَشَبَّ الرَّجُلُ بَنِينَ</foreign> (tropical:)  <hi rend="ital">the man
became one whose children had attained to that
state:</hi> (S, TA:) and in like manner, <foreign lang="ar">أَشَبَّتْ أَوْلَادًا</foreign>
is said of a woman. (TA.) ― 
       <milestone unit="sense" n="2"/>-b2-  And <foreign lang="ar">أَشَبَّ</foreign> said of
[the species of bovine antelope called] the wild
bull, (S, K,) <hi rend="ital">He became such as is termed</hi> <foreign lang="ar">شَبَبٌ</foreign>
[q. v.], i. e., (S,) <hi rend="ital">he became advanced in age,</hi> or
<hi rend="ital">full-grown;</hi> (<foreign lang="ar">مُسِنّ</foreign>, S, K;) <hi rend="ital">one whose state termed</hi>
<foreign lang="ar">إِسْنَان</foreign> [q. v.] <hi rend="ital">had ended.</hi> (S.)

  </entryFree>
```

...the text `اشبّهُ ٱللّٰهُ` only occurs twice within that block despite there being three instances of a lemma with that text as its key.

So, I'd just be grateful if you could give even just a very high-level introduction to these attributes (assuming this was not just built by some software you were using and are not familiar with all its inner workings).

**Comment by balmas** [comment]
@abrasax can you comment on the TEI structure?

**Comment by abrasax** [comment]
> Hi,
> 
> Although some of the XML mark-up seems based on the Text Encoding Initiative (TEI) dialect of XML, e.g., in use of [`entryFree`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-entryFree.html), the markup seems to differ somewhat, at least from the current TEI version (e.g., adding a `key` attribute to `entryFree`).
> 
> In looking at your indexes of the form:
> 
> ```
>     <entry lemma="اشبّهُ ٱللّٰهُ" key="اشبّهُ ٱللّٰهُ" id="n21523" i="1"/>
>     <entry lemma="اشبّهُ ٱللّٰهُ" key="اشبّه ٱللّه" id="n21523" i="4"/>
>     <entry lemma="اشبّهُ ٱللّٰهُ" key="اشبه ٱلله" id="n21523" i="5"/>
>     <entry lemma="شُبَّ" key="شُبَّ" id="n21523" i="1"/>
>     <entry lemma="شُبَّ" key="شبّ" id="n21523" i="4"/>
>     <entry lemma="شُبَّ" key="شب" id="n21523" i="5"/>
> ```
> 
> I understand `lemma` to be the dictionary-friendly root, and I'm guessing that `key` may be related to the fact that a single entry may have different `<form>`'s perhaps. However, I am not discerning the pattern by which `i` might be used to correspond to tags and their sequence.
> 
> For example, in looking at the following entry (the only referencing `n21523`):
> 
> ```
> <entryFree id="n21523" key="اشبّهُ ٱللّٰهُ" type="main">
>     <form>
>       <itype>4</itype> 
>       <orth orig="" extent="full" lang="ar">اشبّهُ ٱللّٰهُ</orth></form> <hi rend="ital">God made him,</hi> or <hi rend="ital">may God make
> him, to become a youth,</hi> or <hi rend="ital">young man;</hi> i. e.,
> <hi rend="ital">to attain to the state termed</hi> <foreign lang="ar">شَبَابٌ</foreign> <hi rend="ital">meaning as
> expl. below:</hi> and <foreign lang="ar">اشبّ ٱللّٰهُ قَرْنَهُ</foreign> means the same:
> (S, A, TA:) the latter [lit. means <hi rend="ital">God made,</hi> or
> <hi rend="ital">may God make, his equal in age to become a
> youth,</hi> &amp;c., (see Har p. 572,) and therefore] is
> tropical. (A, TA.) ― 
>        <milestone unit="sense" n="2"/>-b2-  <foreign lang="ar">أَشْبَيْتُ الفَرَسَ</foreign> <hi rend="ital">I excited the
> horse to be brisk, lively,</hi> or <hi rend="ital">sprightly, and to raise
> his fore legs together, as though in leaping, and
> to play.</hi> (S, * K, * TA.) ― 
>        <milestone unit="sense" n="2"/>-b3-  <foreign lang="ar">اشبّ النَّارَ</foreign>: see 1. ― 
>        <milestone unit="sense" n="2"/>-b4- 
> <foreign lang="ar">أُشِبَّ لِىَ الرَّجُلُ</foreign>, inf. n. <foreign lang="ar">إِشْبَابٌ</foreign>; as also ↓ <orth type="arrow" lang="ar">شُبَّ</orth>; (tropical:)  <hi rend="ital">The
> man appeared before my upraised eyes when not
> hoped for.</hi> (AZ, TA.) ― 
>        <milestone unit="sense" n="2"/>-b5-  And <foreign lang="ar">أُشِبَّ لِى كَذَا</foreign>, and
> ↓ <orth type="arrow" lang="ar">شُبَّ</orth>, (tropical:)  <hi rend="ital">Such a thing was prepared,</hi> or <hi rend="ital">appointed,</hi>
> or <hi rend="ital">ordained, for me.</hi> (S, K, * TA.) ＝   
>     <milestone unit="sense" n="1"/>-A2-  <foreign lang="ar">أَشَبُّ</foreign> (tropical:)  <hi rend="ital">He
> became one whose child,</hi> or <hi rend="ital">children, had attained
> to the state of</hi> <foreign lang="ar">شَبَاب</foreign> [i. e. <hi rend="ital">youth,</hi> or <hi rend="ital">young manhood,</hi> &amp;c.]: (K:) [or] <foreign lang="ar">أَشَبَّ الرَّجُلُ بَنِينَ</foreign> (tropical:)  <hi rend="ital">the man
> became one whose children had attained to that
> state:</hi> (S, TA:) and in like manner, <foreign lang="ar">أَشَبَّتْ أَوْلَادًا</foreign>
> is said of a woman. (TA.) ― 
>        <milestone unit="sense" n="2"/>-b2-  And <foreign lang="ar">أَشَبَّ</foreign> said of
> [the species of bovine antelope called] the wild
> bull, (S, K,) <hi rend="ital">He became such as is termed</hi> <foreign lang="ar">شَبَبٌ</foreign>
> [q. v.], i. e., (S,) <hi rend="ital">he became advanced in age,</hi> or
> <hi rend="ital">full-grown;</hi> (<foreign lang="ar">مُسِنّ</foreign>, S, K;) <hi rend="ital">one whose state termed</hi>
> <foreign lang="ar">إِسْنَان</foreign> [q. v.] <hi rend="ital">had ended.</hi> (S.)
> 
>   </entryFree>
> ```
> 
> ...the text `اشبّهُ ٱللّٰهُ` only occurs twice within that block despite there being three instances of a lemma with that text as its key.
> 
> So, I'd just be grateful if you could give even just a very high-level introduction to these attributes (assuming this was not just built by some software you were using and are not familiar with all its inner workings).

Brett, I'm afraid your apprehension about the availability of information about the Lane structure it correct; it is both undocumented and poorly remembered. I inherited the project long after it had been keyed and the major structural decisions had been made. As far as i remember, EntryFree was used to avoid rather a lot of more detailed structure. You might want to consult with <winfriedleclaire@gmail.com> who has spent rather a lot of time reformatting Lane to comply with the current TEI dictionary format. A variety of other improvements would be possible, but other commitments have prevented our attempting them.  They include better browsing functionality as well as fulltext  search outside the "keys" currently used. But I cannot say when we might be able to get to this. You might also want to take a look at what Grahame Andrews has done with Lane- very nice browsing in very professional software. https://github.com/laneslexicon.
Sorry not to be able to be of more immediate assistance.
Good luck,  Harry

**Comment by brettz9** [comment]
Understandable! Thank you very much for the information and references! Best wishes...
